mlf_core_version: '1.11.4 # <<MLF-CORE_NO_BUMP>>'
domain: mlflow
language: pytorch
project_slug: test-mlf
project_slug_no_hyphen: test_mlf
template_version: '2.0.0 # <<MLF-CORE_NO_BUMP>>'
template_handle: mlflow-pytorch
github_username: cameronraysmith
creator_github_username: cameronraysmith
is_github_repo: true
is_repo_private: false
is_github_orga: false
full_name: Cameron Smith
email: cameron.ray.smith@gmail.com
project_name: test-mlf
project_short_description: test mlf
version: 0.1.0-SNAPSHOT
license: Affero
